<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<?php
echo "<h1 class='text-dark text-center mt-4 bg-active'>...Welcome to our blog Page...</h1>";
echo "<h4 class='text-muted mt-4 float-start'>If you are already a member,</h4><br>";
echo $this->tag->linkTo(["login", "Login Here!", 'class' => 'btn btn-info mb-2']);
echo PHP_EOL;
echo "<h4 class='text-muted mt-4 float-'>If you aren't a member, </h4><br>";
echo $this->tag->linkTo(["signup", "Register Here!", 'class' => 'btn btn-success mb-2']);
?>